brasileiro = ('Santos', 'Palmeiras', 'Flamengo', 'Atlético-MG', 'São Paulo', 'Corinthians', 'Botafogo', 'Internacional', 'Ceará SC', 'Bahia', 'Atlético-PR', 'Fortaleza', 'Goiás', 'Grêmio', 'Vasco', 'Fluminense', 'Cruzeiro', 'Chapecoense', 'CSA', 'Avaí')
print('-='*140)
print(f'Tabela do Brasileirão: {brasileiro}')
print('-='*140)
print(f'5 primeiros: {brasileiro[:5]}')
print('-='*140)
print(f'5 últimos: {brasileiro[15:]}')
print('-='*140)
print(f'Times em ordem alfabética: {sorted(brasileiro)}')
print('-='*140)
print('A Chapecoense está na {}º posição'.format(brasileiro.index('Chapecoense')+1))
